feat: means table modification
Pinpon-GroupeA/pinpon pull request #19
Opened 2023-05-09 09:19 UTC by LegerLucas

2023-05-09 14:37 UTC, Xorko requested changes
Voir commentaires ci-dessus

2023-05-09 14:37 UTC, Xorko commented on app/intervention/[id]/(tabs)/means/index.tsx
> +  const onInsertMeans = async (mean: any) => {
```suggestion
  const onMeanInserted = async (mean: any) => {
```

A typer

2023-05-09 14:37 UTC, Xorko commented on app/intervention/[id]/(tabs)/means/index.tsx
> +  const onUpdateMeans = async (mean: any) => {
```suggestion
  const onMeanUpdated = async (mean: any) => {
```

A typer

2023-05-09 14:37 UTC, Xorko commented on app/intervention/[id]/(tabs)/means/index.tsx
> +  const onDeleteMeans = (mean: any) =>
```suggestion
  const onMeanDeleted = (mean: any) =>
```

A typer

2023-05-09 14:37 UTC, Xorko commented on app/intervention/[id]/(tabs)/means/index.tsx
> +          onInsertMeans(payload.new as any);
```suggestion
          onMeanInserted(payload.new as any);
```

Pourquoi any ?

2023-05-09 14:37 UTC, Xorko commented on app/intervention/[id]/(tabs)/means/index.tsx
> +          onUpdateMeans(payload.new as any);
```suggestion
          onMeanUpdated(payload.new as any);
```

Même question qu'au dessus

2023-05-09 14:37 UTC, Xorko commented on app/intervention/[id]/(tabs)/means/index.tsx
> +          onDeleteMeans(payload.old as any);
```suggestion
          onMeanDeleted(payload.old as any);
```
Même question qu'au dessus

2023-05-09 14:37 UTC, Xorko commented on app/intervention/[id]/(tabs)/means/index.tsx
> +    queryKey: ['requestMeans'],
```suggestion
    queryKey: ['requestMeans', interventionId],
```

2023-05-09 14:37 UTC, Xorko commented on app/intervention/[id]/(tabs)/means/index.tsx
> +  const onInsertRequests = async (request: any) => {
```suggestion
  const onRequestInserted = async (request: any) => {
```

Type ?

2023-05-09 14:37 UTC, Xorko commented on app/intervention/[id]/(tabs)/means/index.tsx
> +    console.log('les coueilles');
???

2023-05-09 14:37 UTC, Xorko commented on app/intervention/[id]/(tabs)/means/index.tsx
> +    queryClient.setQueryData(['requestMeans'], (old: any[] | undefined) =>
Pourquoi any ?

2023-05-09 14:37 UTC, Xorko commented on components/means/means-table/MeansTable.tsx
> +              <Text flex={2} />
Pourquoi des Text vides ?

2023-05-10 08:13 UTC, agoguebenoit commented on components/means/means-table/MeansTable.tsx
> +              <Text flex={2} />
remplacé par des box

2023-05-10 08:16 UTC, agoguebenoit approved these changes

2023-05-10 08:18 UTC, agoguebenoit approved these changes

2023-05-10 08:19 UTC, agoguebenoit approved these changes

2023-05-10 08:19 UTC, merged